version: '3.8'
services: 
  web_api:
    restart: always
    container_name: 'caro-game-api'
    build:
      context: '.'
    image: ngoctin02806/caro-game-api
    ports:
      - "8010:8000"
      - "8011:8000"
    environment: 
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - GMAIL_REFRESH_TOKEN=${GMAIL_REFRESH_TOKEN}
      - GMAIL_ACCESS_TOKEN=${GMAIL_ACCESS_TOKEN}
      - GOOGLE_APP_CLIENT_ID=${GOOGLE_APP_CLIENT_ID}
      - GOOGLE_APP_CLIENT_SECRET=${GOOGLE_APP_CLIENT_SECRET}
      - FACEBOOK_APP_CLIENT_ID=${FACEBOOK_APP_CLIENT_ID}
      - FACEBOOK_APP_CLIENT_SECRET=${FACEBOOK_APP_CLIENT_SECRET}
      - VIRTUAL_HOST=api.hcmusedu.info
      - VIRTUAL_PORT=8010
      - MONGO_URL=${MONGO_URL}
      - PORT=8000
      - NODE_ENV=development
    depends_on: 
      - mongo
  mongo:
    image: mongo
    container_name: 'mongo-db'
    restart: always
    ports:
      - "27017:27017"
    volumes: 
      -  "/opt/caro-mongo-data:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    command: mongo --auth
networks:
  default:
    external:
      name: my-cicd-network
